# Generated by Django 2.2 on 2020-04-06 20:03

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=DjangoUeditor.models.UEditorField(verbose_name='描述'),
        ),
    ]
